### ISSUE TITLE
cassandra stops cluster - Digest mismatch exception

### ISSUE THREAD

**Issue by jantzen05** [openshift/origin-metrics#396] opened 2017-12-11 15:53 UTC
Running metrics with a cluster setup of 2 nodes we regulary run into an issue with the cassandra cluster stop recieving requests and no metrics is collected.

We see that 
Digest mismatch exception occur, cassandra starts shutdown but is never restarted.
node with issue stops listening on port 9042 but doing a nodetool status is reports cluster state as Up/Normal on both nodes.
Doing nodetoll status on other member and you get information on node with issue as Down.

Cassandra nodes is running on storage provided by gluster.
OpenShift version is 3.6.1
origin-metrics=v3.6.1

Issue seems to be fixed in version 3.0.15
https://issues.apache.org/jira/browse/CASSANDRA-13696

Our fix is to restart the instance with the issue and disable hawkular-metrics during the restart.

Errors seen in the logfile:
ERROR [HintsDispatcher:8] 2017-12-09 15:04:27,139 StorageService.java:427 - Stopping native transport
INFO [HintsDispatcher:8] 2017-12-09 15:04:27,166 Server.java:180 - Stop listening for CQL clients
WARN [HintsDispatcher:8] 2017-12-09 15:04:25,010 HintsReader.java:235 - Failed to read a hint for /10.131.5.38: 82393071-cf8f-4c3f-9480-6c01f48d3bcf - table with id 4842a3f0-dc2f-11e7-a426-f5cb25e9bb25 is unknown in file 82393071-cf8f-4c3f-9480-6c01f48d3bcf-1512831852036-1.hints
ERROR [HintsDispatcher:8] 2017-12-09 15:04:25,044 HintsDispatchExecutor.java:234 - Failed to dispatch hints file 82393071-cf8f-4c3f-9480-6c01f48d3bcf-1512831852036-1.hints: file is corrupted ({})
org.apache.cassandra.io.FSReadError: java.io.IOException: Digest mismatch exception
Caused by: java.io.IOException: Digest mismatch exception
org.apache.cassandra.io.FSReadError: java.io.IOException: Digest mismatch exception

ERROR [HintsDispatcher:8] 2017-12-09 15:04:25,091 StorageService.java:417 - Stopping gossiper
WARN  [HintsDispatcher:8] 2017-12-09 15:04:25,092 StorageService.java:308 - Stopping gossip by operator request
INFO  [HintsDispatcher:8] 2017-12-09 15:04:25,093 Gossiper.java:1490 - Announcing shutdown
INFO  [HintsDispatcher:8] 2017-12-09 15:04:25,093 StorageService.java:1997 - Node hawkular-cassandra-1-bjn6g/10.131.2.106 state jump to shutdown
INFO  [GossipStage:1] 2017-12-09 15:04:25,096 Gossiper.java:1019 - InetAddress /10.131.2.106 is now DOWN
org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId 4842a3f0-dc2f-11e7-a426-f5cb25e9bb25. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.

org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId 4842a3f0-dc2f-11e7-a426-f5cb25e9bb25. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.

**Comment by jantzen05** [comment] 2017-12-12 22:02
The health check script does not raise an issue since it checks it own instance. 
Using nodetool it does not discover that port 9042 has been shutdown and because it's checking it's own IP state it does not discover that the other node is down.



`Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
DN  11   3.97 GB    256          51.6%             host2  rack1
UN  10  3.08 GB    256          48.4%             host1  rack1

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10  2.92 GB    256          48.4%             host1    rack1
UN  11   3.99 GB    256          51.6%             host2    rack1`

**Comment by jsanda** [comment] 2018-01-26 19:57
Looks like you are hitting https://issues.apache.org/jira/browse/CASSANDRA-13696. We will upgrade Cassandra to 3.0.15.

**Comment by jsanda** [comment] 2018-05-04 20:59
I am closing this ticket since the version of Cassandra has been updated to 3.0.15 which fixes the bug.

**Closed by jsanda** 2018-05-04 20:59 UTC

**Comment by wa0011048** [comment] 2018-08-14 09:41
We are using DSE 6.0.1 (cassandra-4.0.0) still seeing similar issue. Can you advice on this please?

ERROR [HintsDispatcher:1] 2018-08-13 16:28:43,867 HintsDispatchExecutor.java:243 - Failed to dispatch hints file 6e0d0f69-9e26-4fd4-ac00-7a9b3402fb3c-1533346345261-1.hints: file is corrupted (java.io.IOException: Digest mismatch exception)
ERROR [HintsDispatcher:1] 2018-08-13 16:28:43,869 CassandraDaemon.java:117 - Exception in thread Thread[HintsDispatcher:1,1,main]
org.apache.cassandra.io.FSReadError: java.io.IOException: Digest mismatch exception
at org.apache.cassandra.hints.HintsReader$BuffersIterator.computeNext(HintsReader.java:299)
at org.apache.cassandra.hints.HintsReader$BuffersIterator.computeNext(HintsReader.java:263)
at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
at org.apache.cassandra.hints.HintsDispatcher.sendHints(HintsDispatcher.java:176)
at org.apache.cassandra.hints.HintsDispatcher.sendHintsAndAwait(HintsDispatcher.java:135)
at org.apache.cassandra.hints.HintsDispatcher.dispatch(HintsDispatcher.java:119)
at org.apache.cassandra.hints.HintsDispatcher.dispatch(HintsDispatcher.java:100)
at org.apache.cassandra.hints.HintsDispatchExecutor$DispatchHintsTask.deliver(HintsDispatchExecutor.java:280)
at org.apache.cassandra.hints.HintsDispatchExecutor$DispatchHintsTask.dispatch(HintsDispatchExecutor.java:262)
at org.apache.cassandra.hints.HintsDispatchExecutor$DispatchHintsTask.dispatch(HintsDispatchExecutor.java:238)
at org.apache.cassandra.hints.HintsDispatchExecutor$DispatchHintsTask.run(HintsDispatchExecutor.java:217)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Digest mismatch exception
at org.apache.cassandra.hints.HintsReader$BuffersIterator.computeNextInternal(HintsReader.java:316)
at org.apache.cassandra.hints.HintsReader$BuffersIterator.computeNext(HintsReader.java:290)
... 16 common frames omitted
ERROR [HintsDispatcher:1] 2018-08-13 16:28:43,872 StorageService.java:433 - Stopping native transport
WARN [GossipStage:1] 2018-08-13 16:28:43,872 StorageService.java:338 - Stopping gossip by internal request (typically an unrecoverable error)
INFO [GossipStage:1] 2018-08-13 16:28:43,872 Gossiper.java:1807 - Announcing shutdown
INFO [HintsDispatcher:1] 2018-08-13 16:28:43,872 PluginManager.java:460 - Deactivating plugins which require native transport
INFO [GossipStage:1] 2018-08-13 16:28:43,873 StorageService.java:2647 - Node /192.168.1.42 state jump to shutdown

**Comment by suipinglu** [comment] 2018-12-03 04:53
same issue under this same version of DSE 6.0.1

got the steps to fix it?
