### ISSUE TITLE
Heapster logs too verbose

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin-metrics#21] opened 2015-10-28 13:11 UTC
Heapster seems to be logging (in its own logs) pretty much all the events it's gathering and every kubelet access:

```
I1027 17:08:25.006839       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/luke/mysql-1-qooo6/2ffbcba9-7cec-11e5-8032-fa163e7fc268/mysql"
I1027 17:08:25.006934       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/luke2/dancer-mysql-example-1-yoaty/305ce7d2-7cec-11e5-8032-fa163e7fc268/dancer-mysql-example"
I1027 17:08:25.007080       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/default/router-2-ldovr/754368be-7ce0-11e5-8032-fa163e7fc268/router"
I1027 17:08:25.007207       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/metrics/hawkular-cassandra-1-il6ik/312a2f0c-7cec-11e5-8032-fa163e7fc268/hawkular-cassandra-1"
I1027 17:08:25.007337       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/metrics/heapster-d0lxc/31735cd2-7cec-11e5-8032-fa163e7fc268/heapster"
I1027 17:08:25.007457       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/default/docker-registry-1-75htv/2f9c7a23-7cec-11e5-8032-fa163e7fc268/registry"
I1027 17:08:25.007654       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/luke/cakephp-mysql-example-1-e3u0g/2faef51b-7cec-11e5-8032-fa163e7fc268/cakephp-mysql-example"
I1027 17:08:25.006819       1 kube_events.go:81] Received new event: api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker-registry-1-fldgr.14112722de23749a", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/events/docker-registry-1-fldgr.14112722de23749a", UID:"95e34558-7cee-11e5-8032-fa163e7fc268", ResourceVersion:"330943", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63581576786, nsec:0, loc:(*time.Location)(0x13e5b40)}}, DeletionTimestamp:(*unversioned.Time)(0xc20867dea0), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-fldgr", UID:"d7d56923-7ce6-11e5-8032-fa163e7fc268", APIVersion:"v1", ResourceVersion:"328772", FieldPath:"implicitly required container POD"}, Reason:"Killing", Message:"Killing with docker id 9a86af736859", Source:api.EventSource{Component:"kubelet", Host:"node2.osv3.example.com"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581576786, nsec:0, loc:(*time.Location)(0x13e5b40)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581576786, nsec:0, loc:(*time.Location)(0x13e5b40)}}, Count:1}
I1027 17:08:25.007784       1 kube_events.go:81] Received new event: api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker-registry-1-ojhv4.141121a1dd73fa50", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/events/docker-registry-1-ojhv4.141121a1dd73fa50", UID:"7eae9416-7ce0-11e5-8032-fa163e7fc268", ResourceVersion:"326946", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63581570734, nsec:0, loc:(*time.Location)(0x13e5b40)}}, DeletionTimestamp:(*unversioned.Time)(0xc20867dfc0), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-ojhv4", UID:"7ea9c5f2-7ce0-11e5-8032-fa163e7fc268", APIVersion:"v1", ResourceVersion:"326864", FieldPath:""}, Reason:"FailedScheduling", Message:"no nodes available to schedule pods", Source:api.EventSource{Component:"scheduler", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581570734, nsec:0, loc:(*time.Location)(0x13e5b40)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581570741, nsec:0, loc:(*time.Location)(0x13e5b40)}}, Count:4}
I1027 17:08:25.007905       1 kube_events.go:81] Received new event: api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker-registry-1-ojhv4.141121a561916de5", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/events/docker-registry-1-ojhv4.141121a561916de5", UID:"87af40d0-7ce0-11e5-8032-fa163e7fc268", ResourceVersion:"326977", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, DeletionTimestamp:(*unversioned.Time)(0xc208666180), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-ojhv4", UID:"7ea9c5f2-7ce0-11e5-8032-fa163e7fc268", APIVersion:"v1", ResourceVersion:"326864", FieldPath:""}, Reason:"Scheduled", Message:"Successfully assigned docker-registry-1-ojhv4 to node1.osv3.example.com", Source:api.EventSource{Component:"scheduler", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, Count:1}
I1027 17:08:25.008022       1 kube_events.go:81] Received new event: api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker-registry-1-ojhv4.141121a56f3d5706", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/events/docker-registry-1-ojhv4.141121a56f3d5706", UID:"87ec7793-7ce0-11e5-8032-fa163e7fc268", ResourceVersion:"326985", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, DeletionTimestamp:(*unversioned.Time)(0xc2086663c0), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-ojhv4", UID:"7ea9c5f2-7ce0-11e5-8032-fa163e7fc268", APIVersion:"v1", ResourceVersion:"326976", FieldPath:"implicitly required container POD"}, Reason:"Pulled", Message:"Container image \"openshift3/ose-pod:v3.0.2.902\" already present on machine", Source:api.EventSource{Component:"kubelet", Host:"node1.osv3.example.com"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581570749, nsec:0, loc:(*time.Location)(0x13e5b40)}}, Count:1}
I1027 17:08:25.007163       1 kubelet.go:110] about to query kubelet using url: "https://172.16.4.47:10250/stats/metrics/hawkular-metrics-vrf7d/315f8291-7cec-11e5-8032-fa163e7fc268/hawkular-metrics"
I1027 17:08:25.008377       1 kube_events.go:81] Received new event: api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker-registry-1-ojhv4.141121a8a986f5fe", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/events/docker-registry-1-ojhv4.141121a8a986f5fe", UID:"902fcfcb-7ce0-11e5-8032-fa163e7fc268", ResourceVersion:"327035", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63581570763, nsec:0, loc:(*time.Location)(0x13e5b40)}}, DeletionTimestamp:(*unversioned.Time)(0xc208666600), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-ojhv4", UID:"7ea9c5f2-7ce0-11e5-8032-fa163e7fc268", APIVersion:"v1", ResourceVersion:"326976", FieldPath:"implicitly required container POD"}, Reason:"Created", Message:"Created with docker id 29c7dc064760", Source:api.EventSource{Component:"kubelet", Host:"node1.osv3.example.com"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63581570763, nsec:0, loc:(*time.Location)(0x13e5b40)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63581570763, nsec:0, loc:(*time.Location)(0x13e5b40)}}, Count:1}
...
```

The log gets huge pretty quickly.

**Comment by sosiouxme** [comment] 2015-10-28 13:12
@mwringe

**Comment by jimmidyson** [comment] 2015-10-28 13:17
Dupe of #20

**Closed** 2015-11-04 19:21 UTC
